creation_rules:
    - pgp: ENC[AES256_GCM,data:k+D+4vv2ugVd3AMNFZMOiCd7kHGYB2wBEmvzoEfyVtS0tuVK1k1eVQ==,iv:K6CMda7/pHZN8IDsJi6gg1FzP+yaMKHdjsEZ5se5fdo=,tag:NPuLslwLgnNq6ejOP0hWrg==,type:str]
sops:
    lastmodified: "2025-08-08T07:21:37Z"
    mac: ENC[AES256_GCM,data:z2a7vPlkEBxY1MwVSr8VJ6eCBrTjNoJPVsFdwi7c5Vc3olOMBq0HNeJ3BkQZtOLfopKi0oTsuZi22paEAHp5FOXeZF5sc1aDC388aGMmc6beay4EnQwprRGofGY1gJR5OCFwnN+4rlr0j/2mseidn+6lvJBqlK6rqWbsN4ctmGY=,iv:j9/aTZG60UH/2kJX29EpsGvq/HpzzQCfD1fGx4fFaCI=,tag:Ur0rur52ir+yX/lsdChoDQ==,type:str]
    pgp:
        - created_at: "2025-08-08T07:21:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DHx/q8Q3WM+sSAQdABtifZAmx61pWeHYBOMtSXeZQpDxGeHs+/BhoLR0gLlow
            Qqag7Hx/wZ1A0yFNsq43r5ARZHBUN64GTs4A9l12EBjPraaNd7qAG++u4ozvyL61
            1GgBCQIQ0gIIHaI8vToqMl3hlTIsXETEogTJyeVaQjF6g2vgAAcG0CNKPWZe6bja
            QR8Hcq5nqc9NkXL9B7w+LmZLWQZX8Z8s9k+Ggs5EzP13hJ88Z8KSnoTcImGREENT
            +8BTbDYPs+05IQ==
            =3040
            -----END PGP MESSAGE-----
          fp: E84A4B864AE012CCCE35C63778EE1814B75CD147
    unencrypted_suffix: _unencrypted
    version: 3.10.2
